### ISSUE TITLE
failed to deploy

### ISSUE THREAD

**Issue by faustinoaq** [kofno/scry#20]
Currently the master branch shows `build error`.

![screenshot_20170809_140802](https://user-images.githubusercontent.com/3067335/29139346-2e687658-7d0c-11e7-8dcb-c9334ed8d3ea.png)

TravisCI ouputs:

```
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - bin/linux/scry (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `new'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/releases.rb:135:in `upload_file'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/releases.rb:116:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/releases.rb:107:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider/releases.rb:107:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:154:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/provider.rb:154:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.7/gems/dpl-1.8.40/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:22:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.7/bin/dpl:22:in `<main>'
failed to deploy
```

/cc @keplersj

**Comment by keplersj** [comment]
Un-tagged commits are passing. Should deploy compressed binaries on the next tagged commit.

**Comment by faustinoaq** [comment]
Seems to be good now.

![screenshot_20170810_050323](https://user-images.githubusercontent.com/3067335/29165691-3d4ae0ac-7d89-11e7-8acd-9b47c0b7ddc0.png)
